version: '3'
networks:
  selenoid:
    driver: bridge

services:
  qabattle:
    image: qapropeller/qa-battle:latest
#    network_mode: bridge
    networks:
     - selenoid
    container_name: qabattle
    ports:
      - 8080:8080

  selenoid:
    image: aerokube/selenoid:latest-release
#    network_mode: bridge
    networks:
      - selenoid
    container_name: selenoid
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/config/:/etc/selenoid/"
      - "$PWD/opt:/opt/selenoid/video"
      - "$PWD/opt:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR="$PWD/opt"
    command: ["-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-capture-driver-logs", "-container-network", "qabattle-selenide_bridge"]
    ports:
      - "4444:4444"
    links:
      - qabattle
